[project]
name = "safe-builtins"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "result",
    "typing-extensions>=4.14.1",
]

[tool.uv.sources]
result = { git = "https://github.com/montasaurus/result" }
