name: CI

on:
  pull_request:
  
  push:
    branches:
      - master

    paths:
      - src/**
      - tests/**

jobs:
  test:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        python-version:
          - '3.13'
          - '3.12.4'
          - '3.11'
          - '3.10'

    name: Tests on Python ${{ matrix.python }}

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version}}
      
      - name: ruff lint
        run: uv run ruff check .

      - name: pytest
        run: uv run pytest
        
      - name: ruff format
        run: uv run ruff format --diff .
